#!/bin/bash

CAF_TAG=LA.UM.8.12.r1-13700-sm8250.0

git remote add qcacld-3.0 https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0
git fetch qcacld-3.0 $CAF_TAG
git merge -s ours --no-commit --allow-unrelated-histories FETCH_HEAD
git read-tree --prefix=drivers/staging/qcacld-3.0 -u FETCH_HEAD
git commit

git remote add qca-wifi-host-cmn https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn
git fetch qca-wifi-host-cmn $CAF_TAG
git merge -s ours --no-commit --allow-unrelated-histories FETCH_HEAD
git read-tree --prefix=drivers/staging/qca-wifi-host-cmn -u FETCH_HEAD
git commit

git remote add fw-api https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/fw-api
git fetch fw-api $CAF_TAG
git merge -s ours --no-commit --allow-unrelated-histories FETCH_HEAD
git read-tree --prefix=drivers/staging/fw-api -u FETCH_HEAD
git commit






git fetch qcacld-3.0 $CAF_TAG
git merge -X subtree=drivers/staging/qca-wifi-host FETCH_HEAD

git fetch qca-wifi-host-cmn $CAF_TAG
git merge -X subtree=drivers/staging/qca-wifi-host FETCH_HEAD

git fetch fw-api $CAF_TAG
git merge -X subtree=drivers/staging/fw-api FETCH_HEAD
